// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.Loden {
    public class VersionInfo {
        public static string appVersion = "2.2.4";
        public static string longVersion = "2.2.4-20230720-56382a6d";
        public static string buildDate = "20230720";
    }
}
