// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.Loden {
    public class VersionInfo {
        public static string appVersion = "2.0.2";
        public static string longVersion = "2.0.2-20220528-ffc2e7ca";
        public static string buildDate = "20220528";
    }
}
